# Generated by Django 5.2.17 on 2026-09-08 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_id",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="资产编号"
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="资产名称")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("电脑", "电脑设备"),
                            ("办公家具", "办公家具"),
                            ("网络设备", "网络设备"),
                            ("软件", "软件/系统"),
                            ("办公电器", "办公电器"),
                            ("其他", "其他"),
                        ],
                        default="其他",
                        max_length=30,
                        verbose_name="资产类别",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("在用", "在用"),
                            ("库存", "库存"),
                            ("维修", "维修"),
                            ("报废", "报废"),
                        ],
                        default="库存",
                        max_length=20,
                        verbose_name="使用状态",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="资产价值(元)",
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(blank=True, null=True, verbose_name="购置日期"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="存放位置"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "资产",
                "verbose_name_plural": "资产",
                "ordering": ["asset_id"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="部门名称"
                    ),
                ),
                (
                    "manager",
                    models.CharField(blank=True, max_length=50, verbose_name="负责人"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="部门描述"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "部门",
                "verbose_name_plural": "部门",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="AssetChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("部门转移", "部门转移"),
                            ("状态变更", "状态变更"),
                            ("位置变更", "位置变更"),
                            ("信息修改", "信息修改"),
                            ("报废", "报废"),
                        ],
                        default="信息修改",
                        max_length=20,
                        verbose_name="变更类型",
                    ),
                ),
                (
                    "old_value",
                    models.CharField(blank=True, max_length=200, verbose_name="变更前"),
                ),
                (
                    "new_value",
                    models.CharField(blank=True, max_length=200, verbose_name="变更后"),
                ),
                (
                    "changed_by",
                    models.CharField(blank=True, max_length=50, verbose_name="经办人"),
                ),
                (
                    "change_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="变更时间"),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="备注"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="assets.asset",
                        verbose_name="资产",
                    ),
                ),
            ],
            options={
                "verbose_name": "资产变更",
                "verbose_name_plural": "资产变更",
                "ordering": ["-change_date"],
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="assets.department",
                verbose_name="所属部门",
            ),
        ),
        migrations.CreateModel(
            name="Requisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=50, verbose_name="领用人")),
                (
                    "purpose",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="领用用途"
                    ),
                ),
                (
                    "borrow_date",
                    models.DateField(auto_now_add=True, verbose_name="领用日期"),
                ),
                (
                    "return_date",
                    models.DateField(blank=True, null=True, verbose_name="归还日期"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("借出", "借出"),
                            ("已归还", "已归还"),
                            ("逾期", "逾期"),
                        ],
                        default="借出",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requisitions",
                        to="assets.asset",
                        verbose_name="资产",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requisitions",
                        to="assets.department",
                        verbose_name="领用部门",
                    ),
                ),
            ],
            options={
                "verbose_name": "资产领用",
                "verbose_name_plural": "资产领用",
                "ordering": ["-borrow_date"],
            },
        ),
    ]
