# Generated by Django 5.2.17 on 2026-09-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_department_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="configuration",
            field=models.CharField(blank=True, max_length=500, verbose_name="配置"),
        ),
        migrations.AddField(
            model_name="asset",
            name="specification",
            field=models.CharField(blank=True, max_length=200, verbose_name="规格"),
        ),
    ]
