# Generated by Django 5.2.17 on 2026-09-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_asset_configuration_asset_specification"),
    ]

    operations = [
        migrations.AddField(
            model_name="requisition",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="预计归还"),
        ),
    ]
