# Generated by Django 5.2.17 on 2026-09-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0004_requisition_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="user",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="实际使用人"
            ),
        ),
    ]
