# Generated by Django 5.2.17 on 2026-09-09 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0005_asset_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="角色名称"
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="编码"),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="说明"),
                ),
                (
                    "is_system",
                    models.BooleanField(default=False, verbose_name="系统内置"),
                ),
                (
                    "can_access_admin",
                    models.BooleanField(default=False, verbose_name="访问后台"),
                ),
                (
                    "view_assets",
                    models.BooleanField(default=True, verbose_name="查看资产库"),
                ),
                (
                    "manage_assets",
                    models.BooleanField(default=False, verbose_name="管理资产库"),
                ),
                (
                    "view_org",
                    models.BooleanField(default=True, verbose_name="查看组织架构"),
                ),
                (
                    "manage_org",
                    models.BooleanField(default=False, verbose_name="管理组织架构"),
                ),
                (
                    "view_requisition",
                    models.BooleanField(default=True, verbose_name="查看资产领用"),
                ),
                (
                    "manage_requisition",
                    models.BooleanField(default=False, verbose_name="管理资产领用"),
                ),
                (
                    "view_change",
                    models.BooleanField(default=True, verbose_name="查看资产变更"),
                ),
                (
                    "manage_change",
                    models.BooleanField(default=False, verbose_name="管理资产变更"),
                ),
                (
                    "manage_users",
                    models.BooleanField(default=False, verbose_name="管理用户/角色"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "角色",
                "verbose_name_plural": "角色",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profiles",
                        to="assets.role",
                        verbose_name="角色",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户档案",
                "verbose_name_plural": "用户档案",
            },
        ),
    ]
