# Generated by Django 5.2.17 on 2026-09-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0006_role_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="responsible",
            field=models.CharField(blank=True, max_length=50, verbose_name="责任人"),
        ),
        migrations.AddField(
            model_name="asset",
            name="serial",
            field=models.CharField(blank=True, max_length=120, verbose_name="序列号"),
        ),
        migrations.AddField(
            model_name="assetchange",
            name="reason",
            field=models.CharField(blank=True, max_length=200, verbose_name="变更原因"),
        ),
        migrations.AlterField(
            model_name="asset",
            name="status",
            field=models.CharField(
                choices=[
                    ("在用", "在用"),
                    ("库存", "库存"),
                    ("借出", "借出"),
                    ("维修", "维修"),
                    ("报废", "报废"),
                ],
                default="库存",
                max_length=20,
                verbose_name="使用状态",
            ),
        ),
        migrations.AlterField(
            model_name="assetchange",
            name="change_type",
            field=models.CharField(
                choices=[("部门转移", "部门转移"), ("状态变更", "状态变更")],
                default="部门转移",
                max_length=20,
                verbose_name="变更类型",
            ),
        ),
    ]
