# Generated by Django 5.2.17 on 2026-09-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0007_asset_responsible_asset_serial_assetchange_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requisition",
            name="status",
            field=models.CharField(
                choices=[("借出", "借出"), ("已归还", "已归还")],
                default="借出",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
