# Generated by Django 5.2.17 on 2026-09-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0009_migrate_requisition_overdue_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="category",
            field=models.CharField(
                choices=[
                    ("笔记本电脑", "笔记本电脑"),
                    ("台式机电脑", "台式机电脑"),
                    ("电脑", "电脑设备"),
                    ("办公家具", "办公家具"),
                    ("网络设备", "网络设备"),
                    ("软件", "软件/系统"),
                    ("办公电器", "办公电器"),
                    ("其他", "其他"),
                ],
                default="其他",
                max_length=30,
                verbose_name="资产类别",
            ),
        ),
    ]
