# Generated by Django 5.2.17 on 2026-09-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0010_alter_asset_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auto_enabled",
                    models.BooleanField(default=False, verbose_name="启用自动备份"),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("1d", "每 1 天"),
                            ("3d", "每 3 天"),
                            ("7d", "每 7 天"),
                            ("on_change", "每次数据库变动"),
                        ],
                        default="1d",
                        max_length=20,
                        verbose_name="自动备份频率",
                    ),
                ),
                (
                    "backup_dir",
                    models.CharField(
                        default="backup",
                        help_text="相对项目根目录即可（默认 backup）；也可填绝对路径",
                        max_length=255,
                        verbose_name="备份目录",
                    ),
                ),
                (
                    "last_backup_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="上次备份时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "数据备份",
                "verbose_name_plural": "数据备份",
            },
        ),
    ]
