# Generated by Django 5.2.17 on 2026-09-10 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0011_backupsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="backupsetting",
            name="schedule_time",
            field=models.TimeField(
                default=datetime.time(22, 0),
                help_text="开启自动备份后，由 Windows 计划任务在每天的该时间点执行备份",
                verbose_name="定时备份时间",
            ),
        ),
    ]
