# Generated by Django 5.2.17 on 2026-09-10 09:17

import datetime
from django.db import migrations, models


def _to_daily(apps, schema_editor):
    """旧值「每 1 天（1d）」统一并入新的「每天定时（daily）」。"""
    BackupSetting = apps.get_model('assets', 'BackupSetting')
    BackupSetting.objects.filter(interval='1d').update(interval='daily')


def _back_to_1d(apps, schema_editor):
    BackupSetting = apps.get_model('assets', 'BackupSetting')
    BackupSetting.objects.filter(interval='daily').update(interval='1d')


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0012_backupsetting_schedule_time"),
    ]

    operations = [
        migrations.RunPython(_to_daily, _back_to_1d),
        migrations.AlterField(
            model_name="backupsetting",
            name="interval",
            field=models.CharField(
                choices=[
                    ("daily", "每天定时"),
                    ("3d", "每隔 3 天"),
                    ("7d", "每隔 7 天"),
                    ("on_change", "每次数据变动"),
                ],
                default="daily",
                max_length=20,
                verbose_name="自动备份频率",
            ),
        ),
        migrations.AlterField(
            model_name="backupsetting",
            name="schedule_time",
            field=models.TimeField(
                default=datetime.time(22, 0),
                help_text="到达该时刻后的第一次访问（含浏览页面）即触发备份，无需写入操作",
                verbose_name="定时备份时间",
            ),
        ),
    ]
