# Generated by Django 5.2.17 on 2026-09-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0013_alter_backupsetting_interval_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_builtin",
            field=models.BooleanField(
                default=False,
                help_text="内置账号不可删除、停用或降级，用于避免系统被锁死",
                verbose_name="系统内置账号",
            ),
        ),
    ]
