# Generated by Django 5.2.17 on 2026-09-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0014_userprofile_is_builtin"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="session_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="记录该账号最近一次登录的会话；普通账号仅允许一台设备在线，超管不受限",
                max_length=64,
                verbose_name="当前登录会话",
            ),
        ),
    ]
