# Generated by Django 5.2.17 on 2026-09-11 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0015_userprofile_session_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetchange",
            name="new_responsible",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="变更后责任人"
            ),
        ),
        migrations.AddField(
            model_name="assetchange",
            name="new_user",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="变更后实际使用人"
            ),
        ),
        migrations.AddField(
            model_name="assetchange",
            name="old_responsible",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="变更前责任人"
            ),
        ),
        migrations.AddField(
            model_name="assetchange",
            name="old_user",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="变更前实际使用人"
            ),
        ),
    ]
