# Generated by Django 5.2.17 on 2026-09-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0016_assetchange_new_responsible_assetchange_new_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requisition",
            name="actual_user",
            field=models.CharField(
                blank=True,
                help_text="选填；留空表示实际使用人同领用人",
                max_length=50,
                verbose_name="实际使用人",
            ),
        ),
    ]
