# Generated by Django 5.2.17 on 2026-09-14 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0017_requisition_actual_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="attachments/%Y/%m/", verbose_name="文件"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=200, verbose_name="文件名"),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="备注"),
                ),
                (
                    "size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="文件大小(字节)"
                    ),
                ),
                (
                    "uploaded_by",
                    models.CharField(blank=True, max_length=50, verbose_name="上传人"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="assets.asset",
                        verbose_name="资产",
                    ),
                ),
            ],
            options={
                "verbose_name": "资产附件",
                "verbose_name_plural": "资产附件",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="时间"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("auth", "登录认证"),
                            ("asset", "资产库"),
                            ("requisition", "资产领用"),
                            ("change", "资产变更"),
                            ("org", "组织架构"),
                            ("user", "用户/角色"),
                            ("backup", "数据备份"),
                            ("attachment", "资产附件"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="模块",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "登录成功"),
                            ("login_fail", "登录失败"),
                            ("logout", "退出登录"),
                            ("create", "新增"),
                            ("update", "修改"),
                            ("delete", "删除"),
                            ("import", "批量导入"),
                            ("backup", "生成备份"),
                            ("restore", "恢复备份"),
                            ("download", "下载"),
                            ("other", "其它"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="动作",
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="操作对象"
                    ),
                ),
                ("detail", models.TextField(blank=True, verbose_name="详情")),
                (
                    "operator",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, verbose_name="操作人"
                    ),
                ),
                (
                    "ip",
                    models.CharField(blank=True, max_length=45, verbose_name="来源 IP"),
                ),
            ],
            options={
                "verbose_name": "操作日志",
                "verbose_name_plural": "操作日志",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at", "category"],
                        name="assets_oper_created_9934d1_idx",
                    )
                ],
            },
        ),
    ]
