# Generated by Django 5.2.17 on 2026-09-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0018_assetattachment_operationlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(default=False, verbose_name="启用邮件提醒"),
                ),
                (
                    "smtp_host",
                    models.CharField(
                        blank=True,
                        help_text="如 smtp.exmail.qq.com",
                        max_length=100,
                        verbose_name="SMTP 服务器",
                    ),
                ),
                (
                    "smtp_port",
                    models.PositiveIntegerField(default=465, verbose_name="SMTP 端口"),
                ),
                (
                    "use_ssl",
                    models.BooleanField(
                        default=True,
                        help_text="端口 465 勾选；587 端口不勾（改用 STARTTLS）",
                        verbose_name="使用 SSL",
                    ),
                ),
                (
                    "smtp_user",
                    models.CharField(
                        blank=True,
                        help_text="通常是发件邮箱地址",
                        max_length=100,
                        verbose_name="SMTP 账号",
                    ),
                ),
                (
                    "smtp_password",
                    models.CharField(
                        blank=True,
                        help_text="加密存储；后台展示为打码",
                        max_length=300,
                        verbose_name="SMTP 密码/授权码",
                    ),
                ),
                (
                    "from_email",
                    models.CharField(
                        blank=True,
                        help_text="留空则使用 SMTP 账号",
                        max_length=100,
                        verbose_name="发件人地址",
                    ),
                ),
                (
                    "send_hour",
                    models.PositiveIntegerField(
                        default=9, verbose_name="每日发送时间（小时 0-23）"
                    ),
                ),
                (
                    "last_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="上次发送时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "邮箱配置",
                "verbose_name_plural": "邮箱配置",
            },
        ),
    ]
