# Generated by Django 5.2.17 on 2026-09-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0019_emailconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="email_notify",
            field=models.BooleanField(
                default=False,
                help_text="勾选后，该角色下的账号（填了邮箱的）会收到逾期提醒等通知邮件",
                verbose_name="邮箱通知",
            ),
        ),
    ]
